
databases:
  - name: postgres
    plan: starter
    databaseName: dinero_production
    user: dinero
 
services:
  - type: web
    name: postgres
    env: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
